name: Build blastFOAM Debian Package

on:
  push:
    branches:
      - "packaging/debian"

jobs:
  build:
    runs-on: ['self-hosted', 'deb', 'openfoam']
    name: Build BlastFoam
    defaults:
      run:
        working-directory: blastfoam-src
    steps:
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path: 'blastfoam-src'
      - name: Build Tar for Cache
        run: tar --mtime='1970-01-01' -czf cache-check.tar.gz Makefile applications debian etc src
      - name: Check Cache
        id: check-cache
        uses: actions/cache@v3
        with:
          path: blastfoam_*.deb
          key: ${{ hashFiles('blastfoam-src/cache-check.tar.gz') }}
      - run: echo ${{ steps.check-cache.outputs.cache-hit }}
      - name: Build from makefile
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
        run: debuild --no-lintian -i -nc -us -uc -b --jobs=10
      - name: Output Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: blastfoam-untested.deb
          path: ${{ github.workspace }}/blastfoam_*.deb
          retention-days: 7

  install-and-validate:
    strategy:
      matrix:
        validationScenario: ['blastFoam/Sod_shockTube', 'blastFoam/solidImpact']
    runs-on: ['self-hosted', 'deb', 'openfoam']
    name: Validate BlastFoam
    needs:
      - build
    steps:
      - name: Download Debian Package
        uses: actions/download-artifact@v3
        with:
          name: blastfoam-untested.deb
          path: ${{ github.workspace }}
      - name: Install Debian Package
        run: sudo dpkg -i blastfoam_*.deb
      - run: ls -la /opt
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path:
            blastfoam-src
      - shell: bash -l {0}
        run: |
          source /opt/openfoam9/etc/bashrc
          source /opt/blastfoam/etc/bashrc
          ./blastfoam-src/validation/${{ matrix.validationScenario }}/Allrun
      - name: Upload Validation Results
        uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: blastfoam-src/validation
          retention-days: 30
      - name: Uninstall Debian Package
        run: sudo dpkg -r blastfoam