name: Build blastFOAM

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build openFOAM
    steps:
      - name: Add Repo
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
      - name: Install openFOAM
        run: sudo apt-get -y install openfoam9
      - name: Create OpenFOAM directory
        run: mkdir -p OpenFOAM && cd OpenFOAM
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path: 'OpenFOAM/'
      - name: Add blastFoam to Bashrc
        run: |
          source ~/OpenFOAM/blastfoam/etc/bashrc
          source ~/.bashrc


