name: Build blastFOAM Debian Package

on:
  push:
    branches:
      - "packaging/debian"

jobs:
  build:
    runs-on: ['self-hosted', 'deb', 'openfoam']
    name: Build BlastFoam
    defaults:
      run:
        working-directory: blastfoam-src
    steps:
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path: 'blastfoam-src'
      - name: Build Tar for Cache
        run: | 
          tar -czf checksum.tar.gz --mtime='UTC 2019-01-01' --group=0 --owner=0 --numeric-owner --sort=name Makefile applications debian etc src
      - name: Check Cache
        id: check-cache
        uses: actions/cache@v3
        with:
          path: blastfoam_*.deb
          key: ${{ hashFiles('blastfoam-src/checksum.tar.gz') }}
      - name: Build from makefile
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
        run: debuild --no-lintian -i -nc -us -uc -b --jobs=10
      - name: Output Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: blastfoam-untested.deb
          path: ${{ github.workspace }}/blastfoam_*.deb
          retention-days: 7

  install-and-validate:
    strategy:
      fail-fast: false
      matrix:
        include:
          - solver: blastFoam
            scenario: Sod_shockTube
          - solver: blastFoam
            scenario: solidImpact #* uses code templates
          - solver: blastFoam
            scenario: 'Sedov/Sedov_2D'
          - solver: blastFoam
            scenario: 'Sedov/Sedov_3D'
          - solver: blastFoam
            scenario: 'KingeryBulmash/KingeryBulmash_wedge'
          - solver: blastFoam
            scenario: 'rateStick/rateStick_1D'
          - solver: blastEulerFoam
            scenario: shockTube_dilute
          - solver: blastEulerFoam
            scenario: shockTube_dense
          - solver: blastEulerFoam
            scenario: shockTube_bidisperse
    runs-on: ['self-hosted', 'deb', 'openfoam']
    name: Validate BlastFoam
    needs:
      - build
    steps:
      - name: Download Debian Package
        uses: actions/download-artifact@v3
        with:
          name: blastfoam-untested.deb
          path: ${{ github.workspace }}
      - name: Install Debian Package
        run: sudo dpkg -i blastfoam_*.deb
      - run: ls -la /opt
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path:
            blastfoam-src
      - name: Run ${{ matrix.solver }}
        shell: bash -l {0}
        run: |
          source /opt/openfoam9/etc/bashrc
          source /opt/blastfoam/etc/bashrc
          ./blastfoam-src/validation/${{ matrix.solver }}/${{ matrix.scenario }}/Allrun
          echo "Run on GH" >> blastfoam-src/validation/run-on-gh.txt
      - name: Upload Validation Results
        uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: |
            blastfoam-src/validation/${{ matrix.solver }}/${{ matrix.scenario }}
            blastfoam-src/validation/run-on-gh.txt
          retention-days: 30
      - name: Uninstall Debian Package
        run: sudo dpkg -r blastfoam