name: Docker Image Build

on:
  push:
    paths-ignore:
      - docker/**

jobs:
  build:
    container: docker
    runs-on: ['self-hosted', X64]
    name: Build Docker Container
    env:
      container-workspace: "/__w/blastfoam-dev/blastfoam-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/synthetik-technologies/blastfoam-dev:latest
          file: docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha, mode=max

