name: Build blastFOAM Debian Package

on:
  push:
    branches:
      - "packaging/debian"

jobs:
  build:
    runs-on: ['self-hosted', 'deb', 'openfoam']
    name: Build BlastFoam
    defaults:
      run:
        working-directory: blastfoam-src
    steps:
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path: 'blastfoam-src'
      - name: Build Tar for Cache
        run: tar -czf cache-check.tar.gz Makefile applications debian etc src
      - name: Check Cache
        id: check-cache
        uses: actions/cache@v3
        with:
          path: blastfoam_*.deb
          key: $(md5sum blastfoam-src/cache-check.tar.gz)
      - name: Build from makefile
        if: ${{ steps.check-cache.outputs.cache-hit == 'false' }}
        run: debuild --no-lintian -i -nc -us -uc -b --jobs=10
      - name: Output Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: blastfoam-untested.deb
          path: ${{ github.workspace }}/blastfoam_*.deb

  install:
    runs-on: ['self-hosted', 'deb', 'openfoam']
    name: Install BlastFoam
    needs:
      - build
    steps:
      - name: Download Debian Package
        uses: actions/download-artifact@v3
        with:
          name: blastfoam-untested.deb
          path: ${{ github.workspace }}
      - name: Install Debian Package
        run: sudo dpkg -i ${{ github.workspace }}/blastfoam_*.deb
      - run: ls -la /opt
