name: Public Deployment

on:
  push:
    branches:
      - "9-push-main-to-public-repo"

env:
  PROD_REPO: "synthetik-technologies/blastfoam-public-test"
  TEST_TAG: "5.2.0-develop.3"

jobs:
  code:
    name: Deploy Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SYN_BOT_READ_WRITE }}

      - name: Push Code Publically
        run: git push --force "https://github.com/${{ env.PROD_REPO }}" HEAD:master

  docker:
    name: Deploy Docker Code
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.SYN_BOT_READ_WRITE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jacobhoehler
          password: ${{ secrets.DOCKERHUB_JH }}

      - name: Pull Image
        run: docker pull "ghcr.io/${{ github.repository }}:${{ env.TEST_TAG }}"
