name: Public Deployment

on:
  push:
    branches:
      - "9-push-main-to-public-repo"

env:
  PROD_REPO: "https://github.com/synthetik-technologies/blastfoam-public-test.git"

jobs:
  code:
    name: Deploy Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SYN_BOT_READ_WRITE }}

      - name: Push Code Publically
        run: git push --force "${{ env.PROD_REPO }}" HEAD:master
