name: Build and Test

on:
  pull_request:

jobs:
  build:
    if: ${{ false }} #* disable for now

    runs-on: ["self-hosted", "deb", "openfoam"]
    name: Build BlastFoam
    defaults:
      run:
        working-directory: blastfoam-src
    steps:
      - name: Checkout blastFOAM
        uses: actions/checkout@v3
        with:
          path: blastfoam-src
      - name: Build Tar for Cache
        #* This creates a cache tarball that can be used to skip builds
        #* in the next step if the files remain unchanged.
        run: |
          tar -czf checksum.tar.gz --mtime='UTC 2019-01-01' --group=0 --owner=0 \
            --numeric-owner --sort=name Makefile applications debian etc src
      - name: Check Cache
        #* Checks the cache tarball and only rebuilds if there were changes
        id: check-cache
        uses: actions/cache@v3
        with:
          path: blastfoam_*.deb
          key: ${{ hashFiles('blastfoam-src/checksum.tar.gz') }}
      - name: Build from makefile
        #* This builds the package from the makefile ONLY if the cache tarball is changed.
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
        run: debuild --no-lintian -i -nc -us -uc -b --jobs=auto
        #* Debuild Flags
        #* --no-lintian: Do not run lintian on the package
        #* -i: Install the package
        #* -nc: Do not clean the build directory (this removes '.orig' files from tests)
        #* -us: Do not sign the package
        #* -uc: Do not sign the changes file
        #* -b: Build binary package
        #* --jobs=10: Run 10 jobs in parallel
      - name: Output Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: blastfoam_untested.deb
          path: ${{ github.workspace }}/blastfoam_*.deb
          retention-days: 31
